from ast import Return
import random

#request the entry of the number (save the number in a variable)
from random import randint



#Random number generated
Ramdom_number = random.randint(1, 10)
#show if the number matches with the computer
#If there is no coincidence repeat the above steps
def Guess_number():
    User_number = 0
    while User_number != Ramdom_number:
        User_number = int(input("Guess the number in a range of 1-10 generated by the system:"))
        if User_number == Ramdom_number:
            print("Congratulations! The number inserted is the same that the number generated")
        elif User_number < Ramdom_number:
            print("The number inserted is lesser than the number generated. Try again")
        else:
            print("The number inserted is greater that the number generates Try again")
    Return
print(Guess_number())